"""Make password_hash nullable

Revision ID: 58acb2ab21cf
Revises: ef69c87b18cd
Create Date: 2025-04-24 15:23:50.261746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58acb2ab21cf'
down_revision = 'ef69c87b18cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
