"""Initial migration

Revision ID: c847aa67be34
Revises: 
Create Date: 2025-04-23 22:57:06.911192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c847aa67be34'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bonuses', schema=None) as batch_op:
        batch_op.drop_index('idx_bonuses_expires')
        batch_op.drop_index('idx_bonuses_user')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('idx_users_rating')
        batch_op.drop_index('idx_users_role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('idx_users_role', ['role'], unique=False)
        batch_op.create_index('idx_users_rating', ['rating'], unique=False)

    with op.batch_alter_table('bonuses', schema=None) as batch_op:
        batch_op.create_index('idx_bonuses_user', ['user_id'], unique=False)
        batch_op.create_index('idx_bonuses_expires', ['expires_at'], unique=False)

    # ### end Alembic commands ###
